package test.model.agg;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.mvc.model.DbRelationshipBean;

/**
 * @author generated by the umleditor
 */
public class A2b_1 extends DbRelationshipBean {

  public A2b_1(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.lang.Long fieldAId;

  public java.lang.Long getAId() {
    refresh(false); // read lazy initialized objects
    return fieldAId;
  }

  public void setAId(java.lang.Long a) {
    java.lang.Long oldValue = fieldAId;
    fieldAId = a;
    firePropertyChange("aId", oldValue, fieldAId);
  }

  public java.lang.Long fieldBId;

  public java.lang.Long getBId() {
    refresh(false); // read lazy initialized objects
    return fieldBId;
  }

  public void setBId(java.lang.Long b) {
    java.lang.Long oldValue = fieldBId;
    fieldBId = b;
    firePropertyChange("bId", oldValue, fieldBId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(A2b_1.class);
    descriptor.addAssociationEnd(ClassA_1.class, "aId", "T_Id_a");
    descriptor.addAssociationEnd(ClassB_1.class, "bId", "T_Id_b");
    return descriptor;
  }
}
