package test.model.agg;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassA_3 extends DbEntityBean {

  public ClassA_3(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.lang.Long fieldBId;

  public java.lang.Long getBId() {
    refresh(false); // read lazy initialized objects
    return fieldBId;
  }

  public void setBId(java.lang.Long b) {
    java.lang.Long oldValue = fieldBId;
    fieldBId = b;
    firePropertyChange("bId", oldValue, fieldBId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassA_3.class);
    descriptor.addManyToOneReferenceId(DbDescriptor.AGGREGATION, "bId", "T_Id_b", new DbMultiplicityRange(1, 1));
    return descriptor;
  }

  @Override
  public Object jdoGetVersion() {
    return null;
  }

  @Override
  public boolean jdoIsDetached() {
    return false;
  }

  @Override
  public Object jdoNewObjectIdInstance(Object o) {
    return null;
  }
}
