/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	(c) by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.util;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite UtilSuite
*/
// JUnitDoclet end javadoc_class
public class UtilSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.jhotdraw.util");

		suite.addTestSuite(ReverseListEnumeratorTest.class);
		suite.addTestSuite(StandardVersionControlStrategyTest.class);
		suite.addTestSuite(VersionManagementTest.class);
		suite.addTestSuite(UndoableHandleTest.class);
		suite.addTestSuite(UndoRedoActivityTest.class);
		suite.addTestSuite(UndoableAdapterTest.class);
		suite.addTestSuite(UndoableToolTest.class);
		suite.addTestSuite(RedoCommandTest.class);
		suite.addTestSuite(UndoCommandTest.class);
		suite.addTestSuite(UndoableCommandTest.class);
		suite.addTestSuite(GraphLayoutTest.class);
		suite.addTestSuite(BoundsTest.class);
		suite.addTestSuite(StorageFormatManagerTest.class);
		suite.addTestSuite(SerializationStorageFormatTest.class);
		suite.addTestSuite(StandardStorageFormatTest.class);
		suite.addTestSuite(PaletteLayoutTest.class);
		suite.addTestSuite(PaletteIconTest.class);
		suite.addTestSuite(IconkitTest.class);
		suite.addTestSuite(GeomTest.class);
		suite.addTestSuite(FloatingTextFieldTest.class);
		suite.addTestSuite(FillerTest.class);
		suite.addTestSuite(CommandMenuTest.class);
		suite.addTestSuite(CommandChoiceTest.class);
		suite.addTestSuite(CommandButtonTest.class);
		suite.addTestSuite(StorableInputTest.class);
		suite.addTestSuite(StorableOutputTest.class);
		suite.addTestSuite(UndoManagerTest.class);
		suite.addTestSuite(ColorMapTest.class);
		suite.addTestSuite(ClipboardTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
