package ch.softenvironment.jomm.genericmodel.assoc;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassA_4 extends DbEntityBean {

  public ClassA_4(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public ClassB_4 fieldB;

  public ClassB_4 getB() {
    refresh(false); // read lazy initialized objects
    return fieldB;
  }

  public void setB(ClassB_4 b) {
    ClassB_4 oldValue = fieldB;
    fieldB = b;
    firePropertyChange("b", oldValue, fieldB);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassA_4.class);
    descriptor.addOneToOne(DbDescriptor.ASSOCIATION, "b", "aId", new DbMultiplicityRange(1, 1));
    return descriptor;
  }
}
