/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	(c) by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.standard;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite StandardSuite
*/
// JUnitDoclet end javadoc_class
public class StandardSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.jhotdraw.standard");

		suite.addTestSuite(PeripheralLocatorTest.class);
		suite.addTestSuite(SingleFigureEnumeratorTest.class);
		suite.addTestSuite(NullDrawingViewTest.class);
		suite.addTestSuite(NullToolTest.class);
		suite.addTestSuite(HandleAndEnumeratorTest.class);
		suite.addTestSuite(InsertIntoDrawingVisitorTest.class);
		suite.addTestSuite(DeleteFromDrawingVisitorTest.class);
		suite.addTestSuite(SelectAllCommandTest.class);
		suite.addTestSuite(FigureAndEnumeratorTest.class);
		suite.addTestSuite(HandleEnumeratorTest.class);
		suite.addTestSuite(StandardFigureSelectionTest.class);
		suite.addTestSuite(FastBufferedUpdateStrategyTest.class);
		suite.addTestSuite(ToolButtonTest.class);
		suite.addTestSuite(ToggleGridCommandTest.class);
		suite.addTestSuite(StandardDrawingViewTest.class);
		suite.addTestSuite(StandardDrawingTest.class);
		suite.addTestSuite(SimpleUpdateStrategyTest.class);
		suite.addTestSuite(SelectionToolTest.class);
		suite.addTestSuite(SelectAreaTrackerTest.class);
		suite.addTestSuite(ReverseFigureEnumeratorTest.class);
		suite.addTestSuite(RelativeLocatorTest.class);
		suite.addTestSuite(PasteCommandTest.class);
		suite.addTestSuite(OffsetLocatorTest.class);
		suite.addTestSuite(NullHandleTest.class);
		suite.addTestSuite(LocatorConnectorTest.class);
		suite.addTestSuite(HandleTrackerTest.class);
		suite.addTestSuite(GridConstrainerTest.class);
		suite.addTestSuite(FigureEnumeratorTest.class);
		suite.addTestSuite(FigureChangeEventMulticasterTest.class);
		suite.addTestSuite(DuplicateCommandTest.class);
		suite.addTestSuite(DragTrackerTest.class);
		suite.addTestSuite(DeleteCommandTest.class);
		suite.addTestSuite(CutCommandTest.class);
		suite.addTestSuite(CreationToolTest.class);
		suite.addTestSuite(CopyCommandTest.class);
		suite.addTestSuite(ConnectionToolTest.class);
		suite.addTestSuite(ConnectionHandleTest.class);
		suite.addTestSuite(ChopBoxConnectorTest.class);
		suite.addTestSuite(ChangeConnectionStartHandleTest.class);
		suite.addTestSuite(ChangeConnectionEndHandleTest.class);
		suite.addTestSuite(ChangeAttributeCommandTest.class);
		suite.addTestSuite(BufferedUpdateStrategyTest.class);
		suite.addTestSuite(SendToBackCommandTest.class);
		suite.addTestSuite(BringToFrontCommandTest.class);
		suite.addTestSuite(LocatorHandleTest.class);
		suite.addTestSuite(BoxHandleKitTest.class);
		suite.addTestSuite(AlignCommandTest.class);
		suite.addTestSuite(FigureChangeAdapterTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
