package test.model.comp;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassB_4 extends DbEntityBean {

  public ClassB_4(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public ClassA_4 fieldA;

  public ClassA_4 getA() {
    refresh(false); // read lazy initialized objects
    return fieldA;
  }

  public void setA(ClassA_4 a) {
    ClassA_4 oldValue = fieldA;
    fieldA = a;
    firePropertyChange("a", oldValue, fieldA);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassB_4.class);
    descriptor.addOneToOne(DbDescriptor.ASSOCIATION, "a", "bId", new DbMultiplicityRange(1, 1));
    return descriptor;
  }
}
