package test.model.comp;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassA_4 extends DbEntityBean {

  public ClassA_4(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.lang.Long fieldBId;

  public java.lang.Long getBId() {
    refresh(false); // read lazy initialized objects
    return fieldBId;
  }

  public void setBId(java.lang.Long b) {
    java.lang.Long oldValue = fieldBId;
    fieldBId = b;
    firePropertyChange("bId", oldValue, fieldBId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassA_4.class);
    descriptor.addOneToOneReferenceId(DbDescriptor.COMPOSITION, "bId", "T_Id_b", new DbMultiplicityRange(1, 1));
    return descriptor;
  }
}
