package ch.softenvironment.jomm.genericmodel;

import ch.softenvironment.jomm.DbObjectServer;
import ch.softenvironment.jomm.genericmodel.agg.A2b_1;
import ch.softenvironment.jomm.genericmodel.agg.ClassA_2;
import ch.softenvironment.jomm.genericmodel.agg.ClassA_3;
import ch.softenvironment.jomm.genericmodel.agg.ClassB_2;
import ch.softenvironment.jomm.genericmodel.assoc.ClassB_4;
import ch.softenvironment.jomm.genericmodel.comp.ClassA_1;
import ch.softenvironment.jomm.genericmodel.comp.ClassA_4;
import ch.softenvironment.jomm.genericmodel.comp.ClassB_3;
import ch.softenvironment.jomm.genericmodel.structattr.ClassB_1;

/**
 * @author generated by the umleditor
 */
public final class ModelUtility {

  public static DbObjectServer buildModel() {
    javax.jdo.PersistenceManagerFactory pmFactory = new ch.softenvironment.jomm.target.xml.XmlObjectServerFactory();
    pmFactory.setConnectionURL("");
    pmFactory.setNontransactionalRead(false);    // NO autoCommit while reading
    pmFactory.setNontransactionalWrite(false);    // NO autoCommit while writing

    DbObjectServer server = (DbObjectServer) pmFactory.getPersistenceManager("", "");
    registerClasses(server);

    return server;
  }

  private ModelUtility() {
  }

  public static void registerClasses(DbObjectServer server) {
    server.register(ClassA_2.class, "ModelAgg_ClassA_2");
    server.register(ch.softenvironment.jomm.genericmodel.structattr.ClassA_2.class, "ModelStructAttr_ClassA_2");
    server.register(ClassA_4.class, "ModelComp_ClassA_4");
    server.register(ClassB_4.class, "ModelAssoc_ClassB_4");
    server.register(ch.softenvironment.jomm.genericmodel.agg.ClassA_4.class, "ModelAgg_ClassA_4");
    server.register(ClassA_1.class, "ModelComp_ClassA_1");
    server.register(ClassB_3.class, "ModelComp_ClassB_3");
    server.register(ClassA_3.class, "ModelAgg_ClassA_3");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassA_4.class, "ModelAssoc_ClassA_4");
    server.register(ch.softenvironment.jomm.genericmodel.agg.ClassB_3.class, "ModelAgg_ClassB_3");
    server.register(ch.softenvironment.jomm.genericmodel.comp.ClassA_2.class, "ModelComp_ClassA_2");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassA_1.class, "ModelAssoc_ClassA_1");
    server.register(ClassB_1.class, "ModelStructAttr_ClassB_1");
    server.register(ch.softenvironment.jomm.genericmodel.comp.ClassB_1.class, "ModelComp_ClassB_1");
    server.register(ClassB_2.class, "ModelAgg_ClassB_2");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassB_3.class, "ModelAssoc_ClassB_3");
    server.register(ch.softenvironment.jomm.genericmodel.comp.ClassB_2.class, "ModelComp_ClassB_2");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.A2b_1.class, "ModelAssoc_a2b_1");
    server.register(ch.softenvironment.jomm.genericmodel.comp.ClassB_4.class, "ModelComp_ClassB_4");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassA_3.class, "ModelAssoc_ClassA_3");
    server.register(A2b_1.class, "ModelAgg_a2b_1");
    server.register(ch.softenvironment.jomm.genericmodel.agg.ClassB_4.class, "ModelAgg_ClassB_4");
    server.register(ch.softenvironment.jomm.genericmodel.agg.ClassA_1.class, "ModelAgg_ClassA_1");
    server.register(ch.softenvironment.jomm.genericmodel.agg.ClassB_1.class, "ModelAgg_ClassB_1");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassB_1.class, "ModelAssoc_ClassB_1");
    server.register(ch.softenvironment.jomm.genericmodel.structattr.ClassA_1.class, "ModelStructAttr_ClassA_1");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassB_2.class, "ModelAssoc_ClassB_2");
    server.register(ch.softenvironment.jomm.genericmodel.assoc.ClassA_2.class, "ModelAssoc_ClassA_2");
    server.register(ch.softenvironment.jomm.genericmodel.structattr.ClassB_2.class, "ModelStructAttr_ClassB_2");
    server.register(ch.softenvironment.jomm.genericmodel.comp.ClassA_3.class, "ModelComp_ClassA_3");
  }
}
