package ch.softenvironment.jomm.demoapp.model;

/*
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.mvc.model.DbEnumeration;

/**
 * @author generated by the umleditor
 */
public final class Phase extends DbEnumeration {

    protected Phase(ch.softenvironment.jomm.DbObjectServer objectServer) {
        super(objectServer);
    }

    /**
     * Return the database mappings for this persistence object.
     *
     * @see ch.softenvironment.jomm.DbObjectServer.register()
     * @see ch.softenvironment.jomm.DbConnection.addDescriptor()
     */
    public static DbDescriptor createDescriptor(/*Class<Phase> dbCode*/) {
        DbDescriptor descriptor = DbEnumeration.createDefaultDescriptor(Phase.class);
        descriptor.setOrdered(true);
        return descriptor;
    }

    public static final String INCEPTION = "Inception";
    public static final String ELABORATION = "Elaboration";
    public static final String CONSTRUCTION = "Construction";
    public static final String TRANSITION = "Transition";

    @Override
    public Object jdoGetVersion() {
        //TODO HIP just added to compile
        return null;
    }

    @Override
    public boolean jdoIsDetached() {
        //TODO HIP just added to compile
        return false;
    }

    @Override
    public Object jdoNewObjectIdInstance(Object o) {
        //TODO HIP just added to compile
        return null;
    }
}
