package ch.softenvironment.jomm.demoapp;
/*
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

import ch.softenvironment.jomm.DbObjectServer;
import ch.softenvironment.jomm.demoapp.model.ProjectSessionBean;

/**
 * @author generated by the umleditor
 * @version $Revision: 1.3 $ $Date: 2007-01-24 17:11:03 $
 */
abstract class RegisterUtility {

    //private RegisterUtility() {}
    public static void registerClasses(DbObjectServer server) {
        // DbChangeableBean
        server.register(ch.softenvironment.jomm.demoapp.model.Activity.class, "Activity");
        server.register(ch.softenvironment.jomm.demoapp.model.Role.class, "Role");
        server.register(ch.softenvironment.jomm.demoapp.model.Person.class, "Person");
        server.register(ch.softenvironment.jomm.demoapp.model.NaturalPerson.class, "NaturalPerson");
        server.register(ch.softenvironment.jomm.demoapp.model.WorkProduct.class, "WorkProduct");
        server.register(ch.softenvironment.jomm.demoapp.model.Project.class, "Project");
        server.register(ch.softenvironment.jomm.demoapp.model.LegalPerson.class, "LegalPerson");

        // DbEnumeration's
        server.register(ch.softenvironment.jomm.demoapp.model.Phase.class, "Phase");
        server.register(ch.softenvironment.jomm.demoapp.model.CompanyType.class, "CompanyType");
        server.register(ch.softenvironment.jomm.demoapp.model.RoleType.class, "RoleType");

        // DbCode's
        server.register(ch.softenvironment.jomm.demoapp.model.CatalogueCode.class, "CatalogueCode");

        //  DbSessionBean
        server.register(ProjectSessionBean.class, null);
    }
}
