/*
 * @(#)FiguresSuite.java
 *
 * Project:     JHotdraw - a GUI framework for technical drawings
 *              http://www.jhotdraw.org
 *              http://jhotdraw.sourceforge.net
 * Copyright:   (c) by the original author(s) and all contributors
 * License:     Lesser GNU Public License (LGPL)
 *              http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.figures;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite FiguresSuite
*/
// JUnitDoclet end javadoc_class
public class FiguresSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.jhotdraw.figures");

		suite.addTestSuite(NullConnectorTest.class);
		suite.addTestSuite(NullFigureTest.class);
		suite.addTestSuite(UngroupCommandTest.class);
		suite.addTestSuite(ShortestDistanceConnectorTest.class);
		suite.addTestSuite(ScribbleToolTest.class);
		suite.addTestSuite(RectangleFigureTest.class);
		suite.addTestSuite(RoundRectangleFigureTest.class);
		suite.addTestSuite(PolyLineHandleTest.class);
		suite.addTestSuite(PolyLineConnectorTest.class);
		suite.addTestSuite(NumberTextFigureTest.class);
		suite.addTestSuite(LineFigureTest.class);
		suite.addTestSuite(InsertImageCommandTest.class);
		suite.addTestSuite(ImageFigureTest.class);
		suite.addTestSuite(GroupFigureTest.class);
		suite.addTestSuite(GroupCommandTest.class);
		suite.addTestSuite(FontSizeHandleTest.class);
		suite.addTestSuite(EllipseFigureTest.class);
		suite.addTestSuite(ElbowHandleTest.class);
		suite.addTestSuite(ElbowConnectionTest.class);
		suite.addTestSuite(TextToolTest.class);
		suite.addTestSuite(ConnectedTextToolTest.class);
		suite.addTestSuite(ChopEllipseConnectorTest.class);
		suite.addTestSuite(BorderToolTest.class);
		suite.addTestSuite(BorderDecoratorTest.class);
		suite.addTestSuite(ArrowTipTest.class);
		suite.addTestSuite(FigureAttributesTest.class);
		suite.addTestSuite(TextFigureTest.class);
		suite.addTestSuite(PolyLineFigureTest.class);
		suite.addTestSuite(LineConnectionTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
