package ch.softenvironment.jomm.genericmodel.comp;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassA_1 extends DbEntityBean {

  public ClassA_1(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.util.List fieldB = new java.util.ArrayList();

  public java.util.List getB() {
    refresh(false); // read lazy initialized objects
    return fieldB;
  }

  public void setB(java.util.List b) {
    java.util.List oldValue = fieldB;
    fieldB = b;
    firePropertyChange("b", oldValue, fieldB);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassA_1.class);
    descriptor.addOneToMany(DbDescriptor.COMPOSITION, "b", "aId", new DbMultiplicityRange(0, DbMultiplicityRange.UNBOUND), ClassB_1.class, false);
    return descriptor;
  }
}
