package ch.softenvironment.jomm.genericmodel.structattr;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassA_1 extends DbEntityBean {

  public ClassA_1(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public ClassB_1 fieldB;

  public ClassB_1 getB() {
    refresh(false); // read lazy initialized objects
    return fieldB;
  }

  public void setB(ClassB_1 b) {
    ClassB_1 oldValue = fieldB;
    fieldB = b;
    firePropertyChange("b", oldValue, fieldB);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassA_1.class);
    descriptor.addOneToOne(DbDescriptor.COMPOSITION, "b", "aId", new DbMultiplicityRange(0, 1));
    return descriptor;
  }
}
