package ch.softenvironment.jomm.genericmodel.agg;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassB_2 extends DbEntityBean {

  public ClassB_2(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.lang.Long fieldAId;

  public java.lang.Long getAId() {
    refresh(false); // read lazy initialized objects
    return fieldAId;
  }

  public void setAId(java.lang.Long a) {
    java.lang.Long oldValue = fieldAId;
    fieldAId = a;
    firePropertyChange("aId", oldValue, fieldAId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassB_2.class);
    descriptor.addManyToOneReferenceId(DbDescriptor.ASSOCIATION, "aId", "T_Id_a", new DbMultiplicityRange(1, 1));
    return descriptor;
  }

  @Override
  public Object jdoGetVersion() {
    //TODO HIP just added to compile
    return null;
  }

  @Override
  public boolean jdoIsDetached() {
    //TODO HIP just added to compile
    return false;
  }

  @Override
  public Object jdoNewObjectIdInstance(Object o) {
    //TODO HIP just added to compile
    return null;
  }
}
