package ch.softenvironment.jomm.genericmodel.agg;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassB_1 extends DbEntityBean {

  public ClassB_1(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.util.List fieldAId = new java.util.ArrayList();

  public java.util.List getAId() {
    refresh(false); // read lazy initialized objects
    return fieldAId;
  }

  public void setAId(java.util.List a) {
    java.util.List oldValue = fieldAId;
    fieldAId = a;
    firePropertyChange("aId", oldValue, fieldAId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassB_1.class);
    descriptor.addAssociationAttributed(DbDescriptor.ASSOCIATION, "aId", new DbMultiplicityRange(0, DbMultiplicityRange.UNBOUND), new DbMultiplicityRange(0, DbMultiplicityRange.UNBOUND), A2b_1.class,
        "bId");
    return descriptor;
  }
}
