package test.model.structattr;

import ch.softenvironment.jomm.descriptor.DbDescriptor;
import ch.softenvironment.jomm.descriptor.DbMultiplicityRange;
import ch.softenvironment.jomm.mvc.model.DbEntityBean;

/**
 * @author generated by the umleditor
 */
public class ClassB_1 extends DbEntityBean {

  public ClassB_1(ch.softenvironment.jomm.DbObjectServer objectServer) {
    super(objectServer);
  }

  public java.lang.Long fieldClassA_1_bId;

  public java.lang.Long getClassA_1_bId() {
    refresh(false); // read lazy initialized objects
    return fieldClassA_1_bId;
  }

  public void setClassA_1_bId(java.lang.Long classA_1_b) {
    java.lang.Long oldValue = fieldClassA_1_bId;
    fieldClassA_1_bId = classA_1_b;
    firePropertyChange("classA_1_bId", oldValue, fieldClassA_1_bId);
  }

  public static DbDescriptor createDescriptor() {
    DbDescriptor descriptor = new DbDescriptor(ClassB_1.class);
    descriptor.addOneToOneReferenceId(DbDescriptor.ASSOCIATION, "classA_1_bId", "ClassA_1_b", new DbMultiplicityRange(1, 1));
    return descriptor;
  }
}
